/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/person": {
    /** Create a new person */
    post: operations["createPerson"];
  };
}

export interface components {
  schemas: {
    createPersonRequest: {
      firstName: string;
      lastName: string;
      middleName?: string;
      age: number;
    };
    personResponse: {
      firstName: string;
      lastName: string;
      middleName?: string;
      age: number;
      id: string;
    };
    errorResponse: {
      errors?: components["schemas"]["error"][];
    };
    error: {
      /** a unique identifier for the type of error */
      code?: string;
      /** an informative error message */
      detail?: string;
      status?: number;
    };
  };
}

export interface operations {
  /** Create a new person */
  createPerson: {
    responses: {
      /** Creates a new person. Returns the person */
      201: {
        content: {
          "application/json": components["schemas"]["personResponse"];
        };
      };
      /** Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["errorResponse"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["errorResponse"];
        };
      };
    };
    /** Create person request body body */
    requestBody: {
      content: {
        "application/json": components["schemas"]["createPersonRequest"];
      };
    };
  };
}

export interface external {}
