
openapi: 3.0.0
info:
  title: Example API
  version: 0.0.1
  description: Just an API example.
  contact:
    name: The team
    email: a-team@team.co.uk
servers:
  - url: 'https://www.example-cazoo-dev.co.uk/api/example-api'
    description: Development environment
  - url: 'https://www.example-cazoo-test.co.uk/api/example-api'
    description: Test environment
  - url: 'https://www.example-cazoo.co.uk/api/example-api'
    description: Production environment
paths:
  /person:
    post:
      description: Create a new person
      operationId: createPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createPersonRequest'
        description: Create person request body body
      responses:
        '201':
          description: 'Creates a new person. Returns the person'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/personResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    createPersonRequest:
      title: createPersonRequest
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        age:
          minimum: 0
          type: number
      required:
        - firstName
        - lastName
        - age
    personResponse:
      title: personResponse
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        age:
          type: number
        id:
          type: string
      required:
        - firstName
        - lastName
        - age
        - id
    errorResponse:
      title: errorResponse
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/error'
    error:
      title: error
      type: object
      properties:
        code:
          type: string
          example: VALIDATION_ERROR
          description: a unique identifier for the type of error
        detail:
          type: string
          description: 'an informative error message '
          example: /firstName must be string
        status:
          type: number
          example: 400
